POST http://localhost:8000/api/auth/login/
Content-Type: application/json

{ "username":"amelia","password":"fuck56.@"}

###

POST http://localhost:8000/api/auth/signup/
Content-Type: application/json

{"username": "amelia", "password": "fuck56.@", "email": "amelia@uci.cu"}

###
GET http://localhost:8000/api/auth/test_token/
Content-Type: application/json
Authorization: Token 03c4d7613c7cb002fe7d0dce327ef2c98b424fc2

{}